/curr/ytchen/intel/cnc/0.4/bin/intel64/cnc rician_denoise_2D.cnc
g++ -c -I/curr/ytchen/intel/cnc/0.4/include -O2 -o rician_denoise_2D.o rician_denoise_2D.cpp
g++ -o rician_denoise_2D rician_denoise_2D.o -L/curr/ytchen/intel/cnc/0.4/lib/intel64 -lcnc -ltbb -ltbbmalloc

